### ISSUE TITLE
How can we version the notifications mechanism?

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/notifications#10]

**Comment by elf-pavlik** [comment]
Each subscription type is denoted by IRI. Response from Subscription API includes the type of subscription

https://solid.github.io/notifications/protocol#notification-subscription-response

```jsonld
{
  "@context": "https://www.w3.org/ns/solid/notification/v1",
  "type": "WebSocketSubscription2021",
  "source": "wss://websocket.example/?auth=Ys3KiUq"
}
```

The Server Metadata Resource provides URL of the Subscription API for each supported subscription type.
https://solid.github.io/notifications/protocol#discovery

**Comment by csarven** [comment]
The approach in Pavlik's comment still holds with the change that the ED currently uses the notion of https://solid.github.io/notifications/protocol#notification-channel-types (in place of subscription type) in that the IRI of a notification channel type indicates the unique mechanism.

So for example, the NotificationReceiver will use a value like `http://www.w3.org/ns/solidnotifications#WebSocketChannel2023` for the `protocol` parameter for WebSocket.
