### ISSUE TITLE
Why do notifications use JSON-LD?

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/notifications#12]

**Comment by csarven** [comment]
>Note that the message format could also be negotiated by clients; either during the initial negotiation phase (#296), or when setting up the WebSocket connection. There is probably a preference for the initial negotiation phase in order to not surprise clients after they have made their choice of channel.

Servers can indeed advertise their capability to accept client's preferred serialization for the notifications by including the `notify:accept` ( https://solidproject.org/TR/2022/notifications-protocol-20220509#feature-accept ) as part of the notification channel's `notify:feature` set.

**Comment by RubenVerborgh** [comment]
> Is there anything outstanding in this issue before closing?

Note that this issue was part of my series of questions to clarify the design; I've interviewed @acoburn and written his response. I was purely documenting/scribing here and have no concerns.
