### ISSUE TITLE
Universal Notifications Layer

### ISSUE THREAD

**Issue by brownhoward** [solid/notifications#17]
To hide some of the complexity, would there be any advantage of having a universal notifications layer that will handle common elements of the different subscription types (similar in idea as https://github.com/solid/authorization-panel/issues/253 for authorization)?

_Originally posted by @kevin-inrupt in https://github.com/solid/notifications-panel/pull/3#discussion_r710132036_

**Comment by elf-pavlik** [comment]
I believe https://solid.github.io/notifications/protocol does exactly that.
