### ISSUE TITLE
s/WebhookChannel2023/WebHookChannel2023/

### ISSUE THREAD

**Issue by elf-pavlik** [solid/notifications#179]
I'm currently drafting a draft PR for @jaxoncreed's https://github.com/o-development/solid-notification-client

I noticed that we use different capitalizations for WebSocket and Webhook. I think this might lead to some mistakes, one example is in CSS which uses WebHook instead of Webhook

https://github.com/CommunitySolidServer/CommunitySolidServer/blob/main/src/server/notifications/WebHookChannel2023/WebhookChannel2023Type.ts#L17

I think we should quickly consider changing capitalization in the spec, vocab, and context to have matching
* WebSocket
* WebHook

This way CSS could just keep it as currently implemented and we will lower chances of similar misspelling happening in the future.

**Comment by CxRes** [comment]
No, this is not a mistake. That is how the two standards "brand" themselves. WebSocket and Webhook! 

Our job is to reflect what protocol is being used as a notification channel.

**Comment by elf-pavlik** [comment]
Makes sense @CxRes 

Once we have a test suite available it should prevent any typos in implementations that pass it.
