### ISSUE TITLE
WebSocket protocol format and definition

### ISSUE THREAD

**Issue by acoburn** [solid/notifications#3]
The 0.8 Solid specification includes a [WebSocket API](https://github.com/solid/solid-spec/blob/master/api-websockets.md), which defines a simple line-based interaction between client and server. For example, here is a subscription to a container followed by two notifications for child resources that are created:

```
> sub https://example.com/container
< pub https://example.com/container/1
< pub https://example.com/container/2
```

That design has the advantage of being simple to implement and simple to consume. That said, most WebSocket APIs that I have encountered use a JSON-based format, which provides a more structured format for consumption (the format could even be compact JSON-LD) along with easier points for extension (e.g. what if other keywords are to be added?).

In addition, the [JavaScript API for WebSockets](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket#Constructor) (`WebSocket(url[, protocols])`) includes an optional `protocols` parameter. If this interaction is formalized, would it make sense to define a `solid` protocol that could be used for WebSocket interactions?

**Comment by csarven** [comment]
The data format is JSON-LD. The data model is defined by https://solid.github.io/notifications/protocol#notification-data-model (with proposed update as of this writing: https://github.com/solid/notifications/pull/124 ) and further specifics on WebSocket in https://solid.github.io/notifications/websocket-subscription-2021
