### ISSUE TITLE
Documents including script from dokie.li fail to load.

### ISSUE THREAD

**Issue by elf-pavlik** [solid/notifications#44]
I think we should serve that `.js` form github so it is more reliable.

I had the same issue a while ago and mentioned it during one of the earlier meetings.

![Screen Shot 2022-03-16 at 18 57 33](https://user-images.githubusercontent.com/876431/158715408-b47903e9-e964-45b4-8b9d-b55403b0c0dd.png)

@csarven 

related: https://github.com/solid/notifications-panel/issues/36

**Comment by elf-pavlik** [comment]
I don't think my browser is blocking anything. That script from `dokie.li` usually loads just fine but at times it just fails to load. It just looks like `dokie.li` doesn't work in a reliable manner. Do you have some kind of CDN in front of it?

**Comment by elf-pavlik** [comment]
@csarven please take a look at #50 

> I'd like to understand your issue better. I'd be grateful if you know how we can reduce the size: https://github.com/linkeddata/dokieli

I would suggest using https://chrisbateman.github.io/webpack-visualizer/ to see what gets bundled into that file.

It looks like docile bundles a ton of things. Which of them do you actually use for the spec?

**Comment by csarven** [comment]
I look forward to the day where I can help you understand dokieli and the notion/point of dogfooding. But, today may not be that day.

Thanks for the feedback on the webpack visualizer. We've used such tools back in 2016.. but the situation is a bit more complicated than what appears on the surface - you'll have to see the dirty details... 

Once again, you haven't shown how we can reproduce your error. And I'm genuinely trying to resolve it.

**Comment by elf-pavlik** [comment]
> Can you share the screenshot of your Network tab?
> Are you experiencing the same error on other Web browsers?

This error isn't persistent, it just happens now and then. After #50 I will not even be noticing anymore when that script fails to load.

> I look forward to the day when I can help you understand dokieli and the notion/point of dogfooding. But, today may not be that day.

Please do help me understand, what does I or anyone else who **just wants to read the spec** need that dokieli script for?

**Comment by csarven** [comment]
Closing this issue as 50 seems to help. You can also consider block the script or disable JS.
