### ISSUE TITLE
Relation between storage and notifications source (or agent delivering notification to target)

### ISSUE THREAD

**Issue by elf-pavlik** [solid/notifications#49]
I think we should clarify the assumptions we make about how solid storage hosting resources (topics) relate to party hosting notification source or delivering the notification to the target.

I would like to know if at any point we assume that the same solid storage will host the subscription endpoint (or deliver notifications to the target), or it could be done by a distinct party.

I think details of how that party interacts with solid storage could be left up to implementations. It could be still worth assuming that those two could be two distinct parties.

**Comment by acoburn** [comment]
I would assume that there will be cases where the Solid Storage will be the same entity as the one hosting the subscription endpoints.

I would assume that there will also be cases where the opposite holds true: the Solid Storage will _not_ be the same entity as the one hosting the subscription endpoints.

**Comment by elf-pavlik** [comment]
Current specification already has distinct
* Resource Server
* Notification Sender

#152 tracks documenting that interactions between those two are left out of scope
