### ISSUE TITLE
(Re)Naming of "Solid Notifications Protocol" specification

### ISSUE THREAD

**Issue by csarven** [solid/notifications#52]
Action of https://github.com/solid/notifications-panel/blob/main/meetings/2022-03-17.md#is-the-solid-notifications-protocol-spec-title-too-broad

>Is the "Solid Notifications Protocol" spec title too broad?
>Within the scope of panel, we have a charter, we do stuff around notifications. Current protocol seems to be focused on subscriptions. Maybe we need to come back to use cases and see if any of them don't fit under the current spec.

**Comment by elf-pavlik** [comment]
The current spec also includes [Notification Data Model](https://elf-pavlik.github.io/notifications/protocol#notification-data-model) and each subscription type defines how the notifications are picked up (from source) or delivered (to target).
