### ISSUE TITLE
Reconsider `notify:source`

### ISSUE THREAD

**Issue by csarven** [solid/notifications#74]
The WIP definition of `notify:source` in the RDF vocab

>The IRI of a resource used by a client to establish a connection to a notification channel.

is suitable towards general purpose use, however, it is tied to / isDefinedBy https://solidproject.org/TR/websocket-subscription-2021#websocketsubscription2021-source (noting that we have an understanding in the PR to use isDefinedBy/seeAlso that will change this eventually).

But the definition in WebSocketSubscription2021 is actually constrained to `wss`.

Essentially, either `notify:source` needs to be reserved for WebSocketSubscription - and if so, that's fine and we need to be more clear - or we leave it open for use by subscription types.

The proposal in the PR is that the term should be tied to the Notifications Protocol, which would be something like e.g.:

```
isDefinedBy http://www.w3.org/ns/solid/notifications#
seeAlso https://solidproject.org/TR/notifications-protocol#notify-source
```

`#notify-source` will be described under Terminology (or possibly another section that may be more suitable later.)

_Originally posted by @csarven in https://github.com/solid/vocab/pull/62#discussion_r889526008_

**Comment by elf-pavlik** [comment]
Thinking more about human audiences

* We should have a clear definition of *Subscription Response* #57 (in the Protocol)
* We should have a broad, not specific to subtype, definition of what *source* means on *Subscription Response* (in the Protocol)
* Each *source* based subscription type should provide more specific requirements on *source* used on *Subscription Response* (in each sub type)

I think once we get it clear for the human audience (which I assume to be the primary one), we can worry about stating it in RDF, which some secondary audiences might potentially start using in some undefined future.

**Comment by csarven** [comment]
As part of major overhaul of updating the data model ( https://github.com/solid/notifications/pull/135 ) `receiveFrom` replaces `source` and is available for all notification channel types. The vocab uses isDefinedBy as suggested above in https://github.com/solid/vocab/pull/85 . seeAlso will follow.
